export const videoList = [
    {
        title: "for when it’s warmer",
        videoId: "hG6YzmvbosI",
        videoOwnerChannelTitle: "sleepy fish - Topic",
        videoOwnerChannelId: "UCNR1Pzl2T9biZWAbOXZPUwQ",
    },
    {
        title: "Lofi Hip Hop | Leaves",
        videoId: "F1tAoCuof6c",
        videoOwnerChannelTitle: "TSN Vibes",
        videoOwnerChannelId: "UC1Z4DDUyXeGFSIL7FR-vFQg",
    },
    {
        title: "Chilling With Lofi",
        videoId: "M6zDqbdYLYo",
        videoOwnerChannelTitle: "Sad Music - Topic",
        videoOwnerChannelId: "UC9snFmgnSARriqBNhk4D_cw",
    },
    {
        title: "Peaceful Sleep",
        videoId: "XPpYWLl-O10",
        videoOwnerChannelTitle: "No Spirit - Topic",
        videoOwnerChannelId: "UCraRksyJpUyJQexB7-hdoTQ",
    },
    {
        title: "2021 Is All Jazz",
        videoId: "fHXaNXA_NKc",
        videoOwnerChannelTitle: "Lofi Sleep Chill & Study - Topic",
        videoOwnerChannelId: "UC1itStv5HQODNJr1zyUmDyg",
    },
    {
        title: "Blankets",
        videoId: "HdXrkgZP438",
        videoOwnerChannelTitle: "Aso - Topic",
        videoOwnerChannelId: "UCgWzwhihlRaf6t4Bu8cRh6w",
    },
    {
        title: "When I See You",
        videoId: "xbxW2_icZjM",
        videoOwnerChannelTitle: "Kudasaibeats - Topic",
        videoOwnerChannelId: "UCumJMf6sc_oiLpIElQWUiOQ",
    },
    {
        title: "Birds",
        videoId: "xoopso_csJE",
        videoOwnerChannelTitle: "Allem Iversom - Topic",
        videoOwnerChannelId: "UC7oHoI9Xs-QAR81y6TjikyA",
    },
    {
        title: "Rainforest",
        videoId: "Arx6UcDo0T0",
        videoOwnerChannelTitle: "Saib - Topic",
        videoOwnerChannelId: "UCw02oGFeqYXl14LcyKhOTYw",
    },
    {
        title: "Silience",
        videoId: "cyKX1uZgtt8",
        videoOwnerChannelTitle: "Toonorth - Topic",
        videoOwnerChannelId: "UCF_6iylCppB8bwhnW3HmcRw",
    },
    {
        title: "Move Together",
        videoId: "atOeCrsxNoE",
        videoOwnerChannelTitle: "Yasper - Topic",
        videoOwnerChannelId: "UCo0JVM02GNDSKXAoE4JrUYQ",
    },
    {
        title: "Slow Drive",
        videoId: "wy1R4zcBNZ4",
        videoOwnerChannelTitle: "ChillHop - Topic",
        videoOwnerChannelId: "UCvuWT6OEzQga3mNlgInpYnQ",
    },
    {
        title: "Meaux",
        videoId: "aPHPbb2kFz4",
        videoOwnerChannelTitle: "Ian Ewing - Topic",
        videoOwnerChannelId: "UC93IJn52Fc5tVWcSA3GHbzg",
    },
    {
        title: "Soulful",
        videoId: "fs0BCIUQ7Ws",
        videoOwnerChannelTitle: "L'Indécis - Topic",
        videoOwnerChannelId: "UCxXn2yb4qJbG0bKmr3wa4JA",
    },
    {
        title: "Daybreak",
        videoId: "y3PKcVd7UtM",
        videoOwnerChannelTitle: "cocabona - Topic",
        videoOwnerChannelId: "UCGufCXbmC64ajXVhIaCTpqw",
    },
    {
        title: "Velocities",
        videoId: "JgI6z6aQhEA",
        videoOwnerChannelTitle: "sleepy fish - Topic",
        videoOwnerChannelId: "UCNR1Pzl2T9biZWAbOXZPUwQ",
    },
    {
        title: "2020",
        videoId: "xuXUkynqITU",
        videoOwnerChannelTitle: "idealism - Topic",
        videoOwnerChannelId: "UCOc-AHiKRo_Z8rSHPM74Wag",
    },
    {
        title: "Your Favorite Place",
        videoId: "xaVAPmR6JMg",
        videoOwnerChannelTitle: "Joey Pecoraro - Topic",
        videoOwnerChannelId: "UCT2-ZDqZq35BUz_gA7tYRWg",
    },
    {
        title: "Forest Lake Walk",
        videoId: "qGVMBirxwWc",
        videoOwnerChannelTitle: "No Spirit - Topic",
        videoOwnerChannelId: "UCraRksyJpUyJQexB7-hdoTQ",
    },
    {
        title: "faces",
        videoId: "S8p0crahq3A",
        videoOwnerChannelTitle: "Austin Chen - Topic",
        videoOwnerChannelId: "UCrsVHlnA_bA6kZ7rQW8ZnbA",
    },
    {
        title: "Soul Food",
        videoId: "XznpSTBVliM",
        videoOwnerChannelTitle: "Ruck P - Topic",
        videoOwnerChannelId: "UCdltCBFLglVYUCuyvMEk7BA",
    },
    {
        title: "Hanging Lanterns",
        videoId: "cukiBQ18NgE",
        videoOwnerChannelTitle: "Kalaido - Topic",
        videoOwnerChannelId: "UCnX3dJnTo1kf0zZuPcED_FA",
    },
    {
        title: "Valley",
        videoId: "yApGAVGvKDs",
        videoOwnerChannelTitle: "Leavv   - Topic",
        videoOwnerChannelId: "UC7l9fvTjR75Ul_Zexmb5z-w",
    },
    {
        title: "Lofi Chill",
        videoId: "h6TzXFARexQ",
        videoOwnerChannelTitle: "Sad Music - Topic",
        videoOwnerChannelId: "UC9snFmgnSARriqBNhk4D_cw",
    },
    {
        title: "Jazzy Nights",
        videoId: "Rq6Z-HzojV0",
        videoOwnerChannelTitle: "Lofi Sleep Chill & Study - Topic",
        videoOwnerChannelId: "UC1itStv5HQODNJr1zyUmDyg",
    },
    {
        title: "Velvet Garden",
        videoId: "ULgPNlTfinM",
        videoOwnerChannelTitle: "City Girl - Topic",
        videoOwnerChannelId: "UCWGqmBzWyhxn8a-YDSfb_LA",
    },
    {
        title: "Whale Call",
        videoId: "zIo1kXQuVz0",
        videoOwnerChannelTitle: "Saib - Topic",
        videoOwnerChannelId: "UCw02oGFeqYXl14LcyKhOTYw",
    },
    {
        title: "Lunar Drive",
        videoId: "WryLH9_cRkM",
        videoOwnerChannelTitle: "Mondo Loops - Topic",
        videoOwnerChannelId: "UCNFKlIyDJTdmV1oeHdSZ0Xg",
    },
    {
        title: "Wistful",
        videoId: "n9LXXyHjg3w",
        videoOwnerChannelTitle: "Toonorth - Topic",
        videoOwnerChannelId: "UCF_6iylCppB8bwhnW3HmcRw",
    },
    {
        title: "Pastel Plains",
        videoId: "Eh0ooPop5Ps",
        videoOwnerChannelTitle: "fantompower - Topic",
        videoOwnerChannelId: "UCVP1F5TF-aBurJkAdPMpW6g",
    },
];

